<div class="container">
    <div class="jumbotron jumbotron-fluid" style="background: rgba(220,224,234, 0.8)">
        <p class="text-center">think of the meaning</p>

        <form action="functioncalling.php">
            <input type="text" name="txt" />
            <input type="submit" name="insert" value="insert" onclick="insert()" />
            <input type="submit" name="select" value="select" onclick="select()" />
        </form>

</div>
