<?php echo $this->tag->linkTo([
                    '/',
                    'Home',
                    "class" => "btn btn-light btn-lg pull-right",
                    "style" => "text-align: center;",
                ]);
            ?>

<div class="container">
    <div class="jumbotron jumbotron-fluid" style="background: rgba(220,224,234, 0.8)">
        <h1>Start learning</h1>
        <p>Easier said than done</p>

        

<?php echo $this->tag->linkTo([
                    'Learn',
                    'Start Learning',
                    "class" => "btn btn-light btn-lg pull-right",
                    "style" => "text-align: center;",
                ]);
            ?>



<h3>Cards in this deck</h3>"

<?php echo $this->tag->form("List/cards/" . $deck_id); ?>

        <label for="name"></label>
        <?php echo $this->tag->textField("name"); ?>
        <?php echo $this->tag->submitButton("Search"); ?>


</form>

<!-- <form action="Core/search">
            <input type="text" name="query" />
            <input type="submit" />
        </form> -->

     <?php
if ($cards->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Size</th>
            <th>Weight</th>
            <th>Time</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="5">cards quantity: <?php echo $cards->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php
        //$decks = Decks::find(["name = 'Buku'"]); 
        foreach ($cards as $card) {
        if($card->deck_id === $deck_id){
            if($sq !== NULL){
                if(strpos($card->front, $sq) !== false || strpos($card->back, $sq) !== false){?>
                    <tr>
                        <td><?php echo $card->id; ?></td>
                        <td><?php echo $card->front; ?></td>
                        <td><?php echo $card->back; ?></td>
                        <td><?php echo $card->weight; ?></td>
                        <td><?php echo $card->time; ?></td>
                        <td><?php echo $this->tag->linkTo(["List/edit/" . $card->deck_id . "/". $card->id, "Edit"]); ?></td>
                    </tr>

            <?php }} 
            else{?>
                <tr>
                    <td><?php echo $card->id; ?></td>
                    <td><?php echo $card->front; ?></td>
                    <td><?php echo $card->back; ?></td>
                    <td><?php echo $card->weight; ?></td>
                    <td><?php echo $card->time; ?></td>
                    <td><?php echo $this->tag->linkTo(["List/edit/" . $card->deck_id . "/". $card->id, "Edit"]); ?></td>
                </tr>
        <?php }}} ?>
        </tbody>
    </table>
    <?php
}
?>


<?php echo $this->tag->form("List/add/" . $deck_id); ?>


        <label for="front">Front</label>
        <?php echo $this->tag->textField("front"); ?>



        <label for="back">Back</label>
        <?php echo $this->tag->textField("back"); ?>


        <?php echo $this->tag->submitButton("Add"); ?>


</form>




