<?php
        if($success && $message ){
    ?>
<div class = "container">
    <div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
        <?php echo $message; ?>

</div>

<?php
        }
    ?>

<div class = "container">
    <div class="jumbotron jumbotron-fluid" style="background: rgba(220,224,234, 0.8)">

        <?php 
                echo $this->tag->linkTo(['/List/cards/' . $deck_id , 'Go back', 'class' => 'btn btn-primary']);
        ?>

        <br />

        <br />
            
            <?php
                if($currentCard){
                    echo $currentCard->front;
                    ?>
                    
        <br />
                    <?php echo $this->tag->linkTo([
                        'List/reveal/' . $deck_id . '/' . $currentCard->id,
                        'Reveal',
                        "class" => "btn btn-light btn-lg pull-right",
                        "style" => "text-align: center;",
                    ]);}
                else{?>
                    <h1>Good job!</h1>
                    <p>All cards in deck learned for today</p>
                <?php }
                    ?>
    </div>
</div>