<div class = "container">
    <div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
        <?php echo $message; ?>
    </div>

    <?php 
        if($success === true){
            echo $this->tag->linkTo(['/Core', 'Go back', 'class' => 'btn btn-primary']); }
        else{
            echo $this->tag->linkTo(['/Core/add', 'Go back', 'class' => 'btn btn-primary']); }
    ?>
</div>