<?php echo $this->tag->linkTo([
                    '/',
                    'Home',
                    "class" => "btn btn-light btn-lg pull-right",
                    "style" => "text-align: center;",
                ]);
            ?>


<div class="container">
    <div class="jumbotron jumbotron-fluid" style="background: rgba(220,224,234, 0.8)">
        <h1>Start learning</h1>
        <p>Easier said than done</p>

        

<?php echo $this->tag->linkTo([
                    'List/learn/1',
                    'Start Learning',
                    "class" => "btn btn-light btn-lg pull-right",
                    "style" => "text-align: center;",
                ]);
            ?>



<h3>Your Decks</h3>"

<?php echo $this->tag->form("Core"); ?>

        <label for="name"></label>
        <?php echo $this->tag->textField("name"); ?>
        <?php echo $this->tag->submitButton("Search"); ?>


</form>

<!-- <form action="Core/search">
            <input type="text" name="query" />
            <input type="submit" />
        </form> -->

     <?php
if ($decks->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Size</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="5">decks quantity: <?php echo $decks->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php
        foreach ($decks as $deck) {
            if($sq !== NULL){
                if(strpos($deck->name, $sq) !== false){?>
                    <tr>
                        <td><?php echo $deck->id; ?></td>
                        <td><?php echo $deck->name; ?></td>
                        <td><?php 
                                $size = 0;
                                foreach($cards as $card){
                                    if($card->deck_id === $deck->id){
                                        $size++;
                                    }
                                }echo $size; ?></td>
                        <td><?php echo $this->tag->linkTo(["List/learn/" . $deck->id, "Learn"]); ?></td>
                        <td><?php echo $this->tag->linkTo(["List/cards/" . $deck->id, "List"]); ?></td>
                    </tr>
            <?php }} 
            else{?>
                <tr>
                    <td><?php echo $deck->id; ?></td>
                    <td><?php echo $deck->name; ?></td>
                    <td><?php 
                                $size = 0;
                                foreach($cards as $card){
                                    if($card->deck_id === $deck->id){
                                        $size++;
                                    }
                                }echo $size; ?></td>
                    <td><?php echo $this->tag->linkTo(["List/learn/" . $deck->id, "Learn"]); ?></td>
                    <td><?php echo $this->tag->linkTo(["List/cards/" . $deck->id, "List"]); ?></td>
                </tr>
        <?php }} ?>
        </tbody>
    </table>
    <?php
}
?>


<?php echo $this->tag->linkTo([
                    'Core/Add',
                    'Add more',
                    "class" => "btn btn-light btn-lg pull-right",
                    "style" => "text-align: right;",
                ]);
            ?>

</div>




