
<div class="container">
    <div class="jumbotron jumbotron-fluid" style="background: rgba(220,224,234, 0.8)">
        <h1>Start learning</h1>
        <p>Easier said than done</p>

        

<?php echo $this->tag->linkTo([
                    'Learn',
                    'Start Learning',
                    "class" => "btn btn-light btn-lg pull-right",
                    "style" => "text-align: center;",
                ]);
            ?>

<?php echo $this->tag->form("Core/search"); ?>

        <label for="name"></label>
        <?php echo $this->tag->textField("name"); ?>
        <?php echo $this->tag->submitButton("Search"); ?>


</form>

<!-- <form action="search">
            <input type="text" name="txt" />
            <input type="submit" />
        </form> -->

     <?php
if ($decks->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Size</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="5">decks quantity: <?php echo $decks->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php
        $decks = Decks::find(); 
        // $decks = $decks->filter(
        //     function ($deck){
        //         if($deck->name === $searchquery){
        //             return $deck;
        //         }
        //     }
        // );
        foreach ($decks as $deck) { 
            if(strpos($deck->name, $sq) !== false){?>
                <tr>
                    <td><?php echo $deck->id; ?></td>
                    <td><?php echo $deck->name; ?></td>
                    <td><?php echo $deck->size; ?></td>
                    <td><?php echo $this->tag->linkTo(["Learn/" . $deck->id, "Learn"]); ?></td>
                    <td><?php echo $this->tag->linkTo(["List/" . $deck->id, "List"]); ?></td>
                </tr>
        <?php }} ?>
        </tbody>
    </table>
    <?php
}
?>


<?php echo $this->tag->linkTo([
                    'Core/Add',
                    'Add more',
                    "class" => "btn btn-light btn-lg pull-right",
                    "style" => "text-align: right;",
                ]);
            ?>

</div>



